version: '3.4'

services:
  brand:
    image: brand
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/bash
    command: -c "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:8080 app.py"
    ports:
      - 8080:8080

