version: '3.4'

services:
  brand:
    image: brand
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/bash
    command: -c "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 A:/git/brand"
    ports:
      - 5678:5678

